
version: '2'
services:
  varnish:
    image: quay.io/opsway/m2-varnish
    ports:
      - 80:80
  app:
    image: quay.io/opsway/m2-php
    environment:
      XDEBUG: bla-bla
      XDEBUG_REMOTE_HOST: 192.168.0.103
      XDEBUG_REMOTE_AUTOSTART: "on"
    volumes:
    - ../project/magento:/app/current
    - ../project/nginx-log:/var/log/nginx/
  web-worker:
    image: quay.io/opsway/m2-nginx
    volumes_from:
      - app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: magento-local-db
      MYSQL_PASSWORD: MYSQL_PASSWD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWD
      MYSQL_USER: magento-local-db
    volumes:
    - ../project/mysql-data:/var/lib/mysql 
  memcache:
    image: memcached
  redis:
    image: redis
